spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatisJpa?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true
    username: root
    password:
    hikari:
      auto-commit: false
      connection-test-query: select 1

    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  jpa:
    entity-scan: top.itfinally.mybatis.jpa.testEntity

#    username: root
#    password:
